# Generated by Django 2.2.6 on 2023-03-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230307_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
