# Generated by Django 2.2.6 on 2023-03-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20230321_1219'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_post_user_like',
        ),
    ]
